# Generated by Django 6.0.6 on 2026-06-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('starter', 'Starter'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('drink', 'Drink')], max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
